### ISSUE TITLE
Add Change Log to the lib

### ISSUE THREAD

**Issue by oshai** [ongres/scram#11]
In jasync-sql there is a [PR](https://github.com/jasync-sql/jasync-sql/pull/219) to start using ongres/scram (this lib).

Trying to understand what is the latest version it seems like 2.1 from readme badges and [maven](https://mvnrepository.com/artifact/com.ongres.scram/client), but the pom is not up-to-date, nor [releases](https://github.com/ongres/scram/releases). So I found it a bit confusing to understand what was changed.

In addition issue https://github.com/ongres/scram/issues/1#issuecomment-503059500 hints there has been some changes in `2.0` (Java7 and full StringPrep) but I haven't seen those in [commit log](https://github.com/ongres/scram/commits/master).

If it's possible to shed light on previous versions and the difference between them, here or as a changelog file it will be great.

Thanks!

**Comment by jorsol** [comment]
Hi @oshai, in the coming weeks we are going to make some maintenance to the repo, and this repo might become a mirror and everything will be in sync. For the moment you can find the latest version on https://gitlab.com/ongresinc/scram.

**Comment by oshai** [comment]
Thanks!
