### ISSUE TITLE
Can you add reference to RFCs/I-Ds in the README?

### ISSUE THREAD

**Issue by Neustradamus** [ongres/scram#16]
Dear @ongres team, @ahachete, @teoincontatto, @begonapm, @jorsol,

Can you add reference to RFCs/I-Ds in the README?
- https://tools.ietf.org/html/rfc5056
- https://tools.ietf.org/html/rfc5929
- If you support too: https://tools.ietf.org/html/rfc9266

Thanks in advance.

**Comment by jorsol** [comment]
This library implements [rfc5802](https://datatracker.ietf.org/doc/html/rfc5802) and [rfc7677](https://datatracker.ietf.org/doc/html/rfc7677), the external security layer required to provide channel binding is out of the scope for this library.

Anyone who needs to extract channel-binding data that can later be used with SCRAM should check for the [Bouncy Castle Crypto APIs](https://www.bouncycastle.org/java.html).
