### ISSUE TITLE
Consider using the JDK java.util.Base64 instead of shaded bouncycastle version

### ISSUE THREAD

**Issue by lukaseder** [ongres/scram#17]
JDK 8 now has a `java.util.Base64` class for encoding and decoding, meaning that once you upgrade your baseline from Java 7 to Java 8, you can remove `com.ongres.scram.common.bouncycastle.base64.Base64` and the other classes in that package. The removal can then be picked up by pgjdbc, which shades this class once again as `org.postgresql.shaded.com.ongres.scram.common.bouncycastle.base64.Base64`, etc.

Benefits:

- Java 8 is a good baseline. You can profit from this in various ways, including availability of lambda expressions and default methods for yourselves
- You can remove some of your outdated code
- Pgjdbc will automatically remove some of their outdated code
- Everyone will have less outdated bytecode in their dependencies

**Comment by jorsol** [comment]
Java 7 was the baseline for SCRAM, but now that PgJDBC moved to Java 8 we can follow.

So the plan is to also use Java 8 as baseline too. Thanks for bring this up.
